gifthunter/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('main.urls', namespace='main')),
    url(r'^admin/', admin.site.urls),
]

main/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

    url(r'^gifts/(?P<owner_id>[0-9]+)/$', views.list_gifts, name='list_gifts'),
    url(r'^gift/new/$', views.new_gift, name='new_gift'),
    url(r'^gift/(?P<gift_id>[0-9]+)/$', views.view_gift, name='view_gift'),
    url(r'^gift/(?P<gift_id>[0-9]+)/edit/$', views.edit_gift, name='edit_gift'),
    url(r'^gift/(?P<gift_id>[0-9]+)/remove/$', views.remove_gift, name='remove_gift'),

    url(r'^user/$', views.view_user, name='view_user'),

    url(r'^claims/$', views.list_claims, name='list_claims'),
    url(r'^claim/(?P<claim_id>[0-9]+)/$', views.view_claim, name='view_claim'),

    url(r'^connections/$', views.view_connections, name='view_connections'),
    url(r'^connection_request/(?P<user_id>[0-9]+)/$', views.connection_request, name='connection_request'),
    url(r'^pending_connection/(?P<connection_request_id>[0-9]+)/$', views.pending_connection, name='pending_connection'),

    url(r'^search_users/$', views.search_users, name='search_users'),

    url(r'^setup/$', views.setup, name='setup'),

    ## These were all stolen from https://github.com/django/django/blob/master/django/contrib/auth/urls.py
    url(r'^login/$', auth_views.login, {'template_name': 'main/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'main/logout.html'}, name='logout'),

]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Gift(models.Model):
    owner = models.ForeignKey(User, verbose_name="Owner")
    name = models.CharField(max_length=255, verbose_name="Name")
    link = models.URLField(max_length=2048, verbose_name="Link", blank=True, null=True)
    description = models.TextField(verbose_name="Description", blank=True, null=True)
    created_at = models.DateField(auto_now=False, auto_now_add=True)
    #updated_at = models.DateField(auto_now=True, auto_now_add=False)
    priority = models.CharField(max_length=20, verbose_name="Priority", choices=(("high", "High"),("medium", "Medium"),("low", "Low")), default="medium")
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def can_view(self, request):
        if request.user == self.owner:
            return True
        # See if these users are connected
        owner_obj = GifthunterUser.objects.filter(id = self.owner.id)[0]
        if owner_obj.is_connected(request):
            return True

        return False

    def can_edit(self, request):
        if not self.can_view(request):
            return False
        if request.user == self.owner:
            return True
        return False

class GifthunterUser(User):
    class Meta:
        proxy = True

    def is_connected(self, request):
        if request.user == self:
            return True
        
        # Look for connections between the two people. Any conection will allow the people to access basic information about each other.  This is ugly and makes me want to cry, but it's late and I want a beer.
        if Connection.objects.all().filter(giftee_id = request.user.id, gifter_id = self.id):
            return True
        if Connection.objects.all().filter(gifter_id = request.user.id, giftee_id = self.id):
            return True

        return False

# A connection is basically "friending" another user, you can see gift wishlists for each other. It used to be one way, hence the names.
class Connection(models.Model):
    giftee = models.ForeignKey(User, verbose_name = "Giftee", related_name = "giftee")
    gifter = models.ForeignKey(User, verbose_name = "Gifter", related_name = "gifter")

    def __str__(self):
        return str(self.giftee) + " connected to " + str(self.gifter)

class ConnectionRequest(models.Model):
    from_user = models.ForeignKey(User, verbose_name = "from_user", related_name = "from_user")
    to_user = models.ForeignKey(User, verbose_name = "to_user", related_name = "to_user")

    def __str__(self):
        return str(self.from_user) + " requesting to connect to " + str(self.to_user)

# A claim is someone "claiming" a gift for another person, in that they intend to get the person that gift. There's no record of the person it's for, as the gift itself will contain that information. The giftee will be informed and have the gift changed to 'non_active' the day of the "reveal_on" date.
class Claim(models.Model):
    owner = models.ForeignKey(User, verbose_name="Owner")
    gift = models.ForeignKey(Gift, verbose_name = "Gift")

    def __str__(self):
        return str(self.owner) + " claiming " + self.gift.name + " for " + str(self.gift.owner)

main/forms.py
from django import forms

from .models import *

class GiftForm(forms.ModelForm):
    class Meta:
        model = Gift
        fields = ["name", "priority", "link", "description"]

class GifthunterUserForm(forms.ModelForm):
    class Meta:
        model = GifthunterUser
        fields = ["first_name", "last_name"]

class UserSearchForm(forms.Form):
    search_param = forms.CharField(label = "Search", max_length = 256)

main/views.py
from django import shortcuts,urls,template,http
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserChangeForm

from .models import *
from .forms import *
from .helpers import *

@login_required
def index(request):
    context = {}
    page_template = template.loader.get_template('main/index.html')

    return http.HttpResponse(page_template.render(context, request))

def setup(request):
    context = {}
    page_template = template.loader.get_template('main/setup.html')

    if len(GifthunterUser.objects.all()) == 0:
        user = GifthunterUser(username="admin", is_superuser = True, is_staff = True)
        user.set_password("admin")
        user.save()
        context["msg"] = "Admin setup, login with admin:admin. You'll want to change the password on the 'Administration' page as well, otherwise someone else will login to this instance."
    else:
        context["msg"] = "Already setup."

    return http.HttpResponse(page_template.render(context, request))

@login_required
def list_gifts(request, owner_id):
    context = {}
    page_template = template.loader.get_template('main/list_gifts.html')

    # Retreve all Gift objects owned by user
    gift_objs = None
    owner_obj = None

    try:
        gift_objs = Gift.objects.all().filter(owner_id = owner_id, active = True)
        owner_obj = GifthunterUser.objects.all().filter(pk = owner_id)[0]
        context["msg"] = request.session.pop("msg", "")
        context["msg_type"] = request.session.pop("msg_type", "")
    except:
        raise http.Http404("Could not retrieve objects.")

    context["owner"] = owner_obj
    context["gifts"] = gift_objs

    return http.HttpResponse(page_template.render(context, request))

@login_required
def view_gift(request, gift_id):
    context = {}
    page_template = template.loader.get_template('main/view_gift.html')

    # Retreve the Gift objects if owned or viewable by current user
    gift_obj = shortcuts.get_object_or_404(Gift, pk = gift_id)

    context["gift"] = gift_obj
    context["msg"] = request.session.pop("msg", "")
    context["msg_type"] = request.session.pop("msg_type", "")
    
    if request.method == "GET":
        pass
    elif request.method == "POST":
        # This part is used exclusively for claiming gifts. Dunno how well this will work.
        
        # Ensure a claim doesn't already exist
        claim_obj = Claim.objects.filter(gift__id = gift_id)
        if claim_obj:
            context["msg"] = "This gift has already been claimed."
            context["msg_type"] = "error"
        else:
            claim_obj = Claim(gift = gift_obj, owner = request.user)
            claim_obj.save()
            context["msg"] = "Gift claimed successfully."
            context["msg_type"] = "success"
    else:
        raise http.Http500("Unknown HTTP method.")
    return http.HttpResponse(page_template.render(context, request))

@login_required
def edit_gift(request, gift_id):
    context = {}
    page_template = template.loader.get_template('main/edit_gift.html')

    # Retreve the Gift objects if owned or viewable by current user
    gift_obj = shortcuts.get_object_or_404(Gift, pk = gift_id)

    if gift_obj.can_edit(request):
        context["gift"] = gift_obj
    else:
        raise http.Http404("Gift not found.")

    if request.method == "GET":
        context["form"] = GiftForm(instance=gift_obj)

    elif request.method == "POST":
        context["form"] = form = GiftForm(request.POST, instance=gift_obj)
        if form.is_valid():
            #This validates the form
            form.save()
            request.session["msg"] = gift_obj.name + " updated successfully"
            request.session["msg_type"] = "success"
            return shortcuts.redirect("main:view_gift", gift_id = gift_obj.id)

        else:
            context["msg"] = "Failed to update Gift"
            context["msg_type"] = "error"
    else:
        raise http.Http500("Unknown HTTP method.")

    return http.HttpResponse(page_template.render(context, request))

@login_required
def new_gift(request):
    context = {}
    page_template = template.loader.get_template('main/edit_gift.html')

    if request.method == "GET":
        context["form"] = GiftForm()

    elif request.method == "POST":
        context["form"] = form = GiftForm(request.POST)
        if form.is_valid():
            # We don't want to commit right away, as we need to set the owner. In theory this will always be the current user.
            gift_obj = form.save(commit = False)
            gift_obj.owner = request.user
            gift_obj.save()

            request.session["msg"] = gift_obj.name + " created successfully"
            request.session["msg_type"] = "success"
            return shortcuts.redirect("main:view_gift", gift_id = gift_obj.id)

        else:
            context["msg"] = "Failed to create new gift"
            context["msg_type"] = "error"
    else:
        raise http.Http500("Unknown HTTP method.")

    return http.HttpResponse(page_template.render(context, request))


@login_required
def remove_gift(request, gift_id):
    context = {}

    # Retreve the Gift objects if owned or viewable by current user
    gift_obj = shortcuts.get_object_or_404(Gift, pk = gift_id)

    if gift_obj.can_edit(request):
        context["gift"] = gift_obj
    else:
        raise http.Http404("Gift not found.")

    if request.method == "GET":
        gift_obj.delete()
        request.session["msg"] = gift_obj.name + " removed successfully"
        request.session["msg_type"] = "success"
        return shortcuts.redirect("main:list_gifts", owner_id = request.user.id)
    else:
        raise http.Http500("Unknown HTTP method.")


# This was originally intended to be a way to view any user, but was reduced to just seeing yourself.
@login_required
def view_user(request):
    context = {}
    page_template = template.loader.get_template('main/view_user.html')

    if request.method == "GET":
        context["form"] = GifthunterUserForm(instance=request.user)

    elif request.method == "POST":
        context["form"] = form = GifthunterUserForm(request.POST, instance=request.user)
        if form.is_valid():
            #This validates the form
            form.save()
            context["msg"] = "Account updated successfully"
            context["msg_type"] = "success"

        else:
            context["msg"] = "Failed to update account"
            context["msg_type"] = "error"
    else:
        raise http.Http500("Unknown HTTP method.")

    return http.HttpResponse(page_template.render(context, request))

@login_required
def view_connections(request):
    context = {}
    page_template = template.loader.get_template('main/view_connections.html')

    context["msg"] = request.session.pop("msg", "")
    context["msg_type"] = request.session.pop("msg_type", "")

    # Retreve all users
    context["users"] = user_objs = User.objects.all().exclude(pk = request.user.id)

    # Retrieve all ConnectionRequests where this user is in the "to_user" field
    context["pending_connections"] = ConnectionRequest.objects.filter(to_user__id = request.user.id)

    return http.HttpResponse(page_template.render(context, request))

@login_required
def search_users(request):
    context = {}
    page_template = template.loader.get_template('main/search_users.html')

    if request.method == "GET":
        context["form"] = form = UserSearchForm()

    elif request.method == "POST":
        context["form"] = form = UserSearchForm(request.POST)

        if form.is_valid():
            # Retreve all connections owned by the current user
            context["user_results"] = user_objs = search_gh_users(form.cleaned_data["search_param"], request.user.id)
            context["is_search"] = True
        else:
            context["msg"] = "Error while searching"
            context["msg_type"] = "error"
    else:
        raise http.Http500("Unknown HTTP method.")

    return http.HttpResponse(page_template.render(context, request))

@login_required
def connection_request(request, user_id):
    context = {}
    page_template = template.loader.get_template('main/connection_request.html')

    # Check to see if these users are already connected, and if so redirect to their list.
    user_obj = shortcuts.get_object_or_404(GifthunterUser, pk = user_id)
    if user_obj.is_connected(request):
        return shortcuts.redirect("main:list_gifts", owner_id = user_id)

    context["to_user"] = user_obj

    if request.method == "GET":
        pass
        # We actually don't need to do anything special here.

    elif request.method == "POST":
        # Check to see if there's already a connection request out
        req_obj = ConnectionRequest.objects.filter(to_user__id = user_id, from_user__id = request.user.id)
        if req_obj:
            # There's already a request out.
            context["msg"] = "Connection request has already been sent"
            context["msg_type"] = "error"
        else:
            connection_request_obj = ConnectionRequest(to_user = user_obj, from_user = request.user)
            connection_request_obj.save()

            context["msg"] = "Sent connection request"
            context["msg_type"] = "success"
            
    else:
        raise http.Http500("Unknown HTTP method.")

    return http.HttpResponse(page_template.render(context, request))
    

@login_required
def pending_connection(request, connection_request_id):
    context = {}
    page_template = template.loader.get_template('main/pending_connection.html')

    # Make sure IDOR isn't an issue here... Although technically the error returned by a non-existent CR is not the same as one that exists, but is for different users, so you could in theory enumerate CR ids. Probably not a huge issue unless there's another way to view CRs, but that's something else entirely.

main/templates/main/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Gifthunter</title>
        <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->
        <link rel=stylesheet type=text/css href="{% static 'css/picnic.min.css' %}">
        <style>
            body {
                max-width: 960px;
                padding: 10px;
                max-width: 960px;
                width: 100%;
                margin: 10px auto 10px;
            }
        </style>
    </head>
    <body>
        <nav>
            <a href="/" class="brand">
                <span>Gifthunter</span>
            </a>
            {% if user.is_authenticated %}

            <input id="bmenu" class="show" type="checkbox">
            <label for="bmenu" class="burger toggle pseudo button">Menu</label>
            <div class="menu">
                {% if user.is_staff %}
                <a href="{% url 'admin:index' %}" class="pseudo button">Administration</a>
                {% endif %}
                <label href="#" class="pseudo button" for="modal_help">Help</label>
                <a href="{% url 'main:view_user' %}" class="pseudo button">Account</a>
                <a href="{% url 'main:logout' %}" class="pseudo button">Logout</a>
            </div>
            {% endif %}
        </nav>

        <div class="modal">
          <input id="modal_help" type="checkbox">
          <label for="modal_help" class="overlay"></label>
          <article>
            <header>
              <h3>Gifthunter Help</h3>
              <label for="modal_help" class="close">×</label>
            </header>
            <section class="content">
              <p>Gifthunter is an application to track and coordinate gifts among groups of people for holidays and birthdays. Use it help people get what they want, without the need to track everything manually.</p>
              <hr />
              <p>Start by finding others in the "Other People" page. Search for people you know so they can see your lists (and vice versa).</p>
              <hr />
              <p>You can track items you'd like to receive on the "My List" page. These can be added at any time, not just around holidays. Items can include a name, a link, a priority, and a description to help others.</p>
              <hr />
              <p>To get a gift for one of your connections, simply visit the list of any of your connections, and "Claim" the gift they'll be recieving from you. After you've gifted it, simply use the "My Claims" page to mark the gift for removal so they don't get it a second time.</p>
            </section>
            <footer>
              <label for="modal_help" class="button">
                Done
              </label>
            </footer>
          </article>
        </div>

        <main style="margin-top: 50px;">
            {% if msg and msg_type%}
            <div>
                <input id="cardtoggle" type="checkbox">
                <div class="button {{ msg_type }} close" style="width: 100%;">
                    {{ msg }}
                </div>
            </div>
            {% endif %}

           {% block base_content %}{% endblock %}
        </main>
    </body>
</html>

main/templates/main/connection_request.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>{% if to_user.first_name %}{% if to_user.last_name %}{{ to_user.first_name }} {{ to_user.last_name }}{% else %}{{ to_user.first_name }}{% endif %}{% else %}{{ to_user }}{% endif %}</h2>
    </header>
    <section>
        <ul>
            {% if to_user.first_name %}
            <li>
                <h3>First Name</h3>
            </li>
            <ul>
                <li>
                    <div>{{ to_user.first_name }}</div>
                </li>
            </ul>
            {% endif %}

            {% if to_user.last_name %}
            <li>
                <h3>Last Name</h3>
            </li>
            <ul>
                <li>
                    <div>{{ to_user.last_name }}</div>
                </li>
            </ul>
            {% endif %}

            {% if to_user.email %}
            <li>
                <h3>Email Address</h3>
            </li>
            <ul>
                <li>
                    <div>{{ to_user.email }}</div>
                </li>
            </ul>
            {% endif %}
        </ul>
        <form method="post" action="">
            {% csrf_token %}
            
            <div class="flex one two-600">
                <div>
                    <button class="success" style="width:100%;" type="submit">Send Connection Request</a>
                </div>
                <div>
                    <a href="{% url 'main:view_connections' %}" class="button error" style="width:100%;">Return to My Connections</a>
                </div>
            </div>
        </form>
    </section>
</article>

{% endblock %}

main/templates/main/index.html
{% extends "main/base.html" %} 
{% load staticfiles %}
{% block base_content %}

<div class="flex two three-500">
    <div style="padding: 6px;">
        <article class="card">
            <a href="{% url 'main:list_gifts' user.id %}"><img src="{% static 'imgs/list.png' %}" style="max-width:100%;"/></a>
            <footer>
                <h3>My List</h3>
            </footer>
        </article>
    </div>

    <div style="padding: 6px;">
        <article class="card">
            <a href="{% url 'main:list_claims' %}"><img src="{% static 'imgs/stamper.png' %}" style="max-width:100%;"/></a>
            <footer>
                <h3>My Claims</h3>
            </footer>
        </article>
    </div>

    <div style="padding: 6px;">
        <article class="card">
            <a href="{% url 'main:view_connections' %}"><img src="{% static 'imgs/group.png' %}" style="max-width:100%;"/></a>
            <footer>
                <h3>Other People</h3>
            </footer>
        </article>
    </div>
</div>
{% endblock %}

main/templates/main/list_claims.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>My Claims</h2>
    </header>
    <section>
        <ul>
            {% for claim in claims %}
            <li>
                <a href="{% url 'main:view_claim' claim.id %}">{{ claim.gift.name }} for {% if claim.gift.owner.first_name %}{% if claim.gift.owner.last_name %}{{ claim.gift.owner.first_name }} {{ claim.gift.owner.last_name }}{% else %}{{ claim.gift.owner.first_name }}{% endif %}{% else %}{{ claim.gift.owner }}{% endif %}</a>
            </li>
            {% endfor %}
            {% if not claims %}
            You have no current claims. View the lists of your connections to claim items.
            {% endif %}
        </ul>
    </section>
</article>
{% endblock %}

main/templates/main/list_gifts.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>
            {% if owner == user  %}My Gift Wishlist{% else %}{% if owner.first_name %}{% if owner.last_name %}{{ owner.first_name }} {{ owner.last_name }}{% else %}{{ owner.first_name }}{% endif %}{% else %}{{ owner }}{% endif %}'s Gift Wishlist{% endif %}</h2>
    </header>
    <section>
        <ul>
            {% for gift in gifts %}
            <li>
                <a href="{% url 'main:view_gift' gift.id %}">[{{ gift.get_priority_display }}] {{ gift }}</a>
            </li>
            {% endfor %}
            {% if not gifts %}
            List is currently empty.{% if owner == user %} Add to the list using the button below!{% endif %}
            {% endif %}
        </ul>
        <div class="flex one">
            {% if owner == user  %}
            <div>
                <a href="{% url 'main:new_gift' %}" class="button" style="width:100%;">Add Gift</a>
            </div>
            {% else %}
            <div>
                <a href="{% url 'main:view_connections' %}" class="button" style="width:100%;">Return to My Connections</a>
            </div>
            {% endif %}
        </div>
    </section>
</article>
{% endblock %}

main/templates/main/search_users.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>User Search</h2>
    </header>
    <section>
        <form method="post" action="">
            {% csrf_token %}

            {{ form.search_param.label_tag }} {{ form.search_param }}
            {% if form.search_param.errors %}
            <ul>
                {% for error in form.search_param.errors %}
                <li>{{ error|escape }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <hr />
            
            <div class="flex one two-600">
                <div>
                    <button class="success" style="width:100%;" type="submit">Search Users</a>
                </div>
                <div>
                    <a href="{% url 'main:view_connections' %}" class="button error" style="width:100%;">Return to My Connections</a>
                </div>
            </div>
        </form>
        {% if is_search %}
        <hr />
        <h3>Unconnected Users</h3>
        <ul>
            {% if not user_results %}
                No results.
            {% else %}
                {% for result in user_results %}
                <li>
                    <a href="{% url 'main:connection_request' result.id %}">
                        <label>                   
                            {% if result.first_name %}
                                {% if result.last_name %}
                                    {{ result.first_name }} {{ result.last_name }}
                                {% else %}
                                    {{ result.first_name }}
                                {% endif %}
                            {% else %}
                                {{ result }}
                            {% endif %}
                            
                        </label>
                    </a>
                </li>
                <!--
                <div class="modal">
                    <input id="modal_{{ result }}" type="checkbox" />
                    <label for="modal_{{ result }}" class="overlay"></label>
                    <article>
                        <header>Connect with {% if result.first_name %}{% if result.last_name %}{{ result.first_name }} {{ result.last_name }}{% else %}{{ result.first_name }}{% endif %}{% else %}{{ result }}{% endif %}</h3>
                            <label for="modal_{{ result }}" class="close">&times;</label>
                        </header>
                        <section class="content">
                            Would you like to send a connection request to {% if result.first_name %}{% if result.last_name %}{{ result.first_name }} {{ result.last_name }}{% else %}{{ result.first_name }}{% endif %}{% else %}{{ result }}{% endif %}?
                        </section>
                        <footer>
                            <a class="button" href="#" onclick="connection_request({{ result.id }})">Send Request</a>
                            <label for="modal_{{ result }}" class="button dangerous">
                                Cancel
                            </label>
                        </footer>
                    </article>
                </div>
                -->
                {% endfor %}
            {% endif %}
        </ul>
        {% endif %}

    </section>
</article>

{% endblock %}

main/templates/main/setup.html
{% extends "main/base.html" %} 
{% block base_content %}
{{ msg }}
{% endblock %}

main/templates/main/view_claim.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>{{ claim.gift.name }}</h2>
    </header>
    <section>
        <ul>
            {% if claim.gift.priority %}
            <li>
                <h3>Priority</h3>
            </li>
            <ul>
                <li>
                    <div class="priority_{{ claim.gift.priority }}">{{ claim.gift.get_priority_display }}</div>
                </li>
            </ul>
            {% endif %}

            {% if claim.gift.link %}
            <li>
                <h3>Link</h3>
            </li>
            <ul>
                <li>
                    <a href="{{ claim.gift.link }}">{{ claim.gift.link }}</a>
                </li>
            </ul>
            {% endif %}

            {% if claim.gift.description %}
            <li>
                <h3>Description</h3>
            </li>
            <ul>
                <li>
                    {{ claim.gift.description }}
                </li>
            </ul>
            {% endif %}
        </ul>
        <div class="flex one two-600">
            <form method="POST" action="">
                {% csrf_token %}
                <div>
                    <input type = "hidden" name="action" value="finalize"/>
                    <input class="button success" style="width:100%;" type="submit" value="Finalize Claim" />
                </div>
            </form>
            <form method="POST" action="">
                {% csrf_token %}
                <div>
                    <input type = "hidden" name="action" value="release"/>
                    <input class="button error" style="width:100%;" type="submit" value="Release Claim" />
                </div>
            </form>
        </div>
        <div class="flex one">
            <div>
                <a href="{% url 'main:list_claims' %}" class="button" style="width:100%;">Return to Claims</a>
            </div>
        </div>
    </section>
</article>

{% endblock %}

main/templates/main/view_gift.html
{% extends "main/base.html" %} 
{% block base_content %}
<article class="card">
    <header>
        <h2>{{ gift.name }}</h2>
    </header>
    <section>
        <ul>
            {% if gift.priority %}
            <li>
                <h3>Priority</h3>
            </li>
            <ul>
                <li>
                    <div class="priority_{{ gift.priority }}">{{ gift.get_priority_display }}</div>
                </li>
            </ul>
            {% endif %}

            {% if gift.link %}
            <li>
                <h3>Link</h3>
            </li>
            <ul>
                <li>
                    <a href="{{ gift.link }}">{{ gift.link }}</a>
                </li>
            </ul>
            {% endif %}

            {% if gift.description %}
            <li>
                <h3>Description</h3>
            </li>
            <ul>
                <li>
                    {{ gift.description }}
                </li>
            </ul>
            {% endif %}
        </ul>
        
        {% if gift.owner == user %}
        <div class="flex one three-600">
            <div>
                <a href="{% url 'main:edit_gift' gift.id %}" class="button" style="width:100%;">Edit Gift</a>
            </div>
            <div>
                <label href="#" class="button" style="width:100%;" for="modal_1">Delete Gift</label>
            </div>
            <div>
                <a href="{% url 'main:list_gifts' gift.owner.id %}" class="button" style="width:100%;">Return to Wishlist</a>
            </div>
        </div>
        <div class="modal">
          <input id="modal_1" type="checkbox">
          <label for="modal_1" class="overlay"></label>
          <article>
            <header>
              <h3>Confirm Gift Deletion</h3>
              <label for="modal_1" class="close">×</label>
            </header>
            <section class="content">
              Are you sure you want to delete {{ gift }}?
            </section>
            <footer>
              <a href="{% url 'main:remove_gift' gift.id %}" class="button">Confirm</a>
              <label for="modal_1" class="button dangerous">
                Cancel
              </label>
            </footer>
          </article>
        </div>

        {% else %}
        <div class="flex one two-600">
            <form method="POST" action="">
                {% csrf_token %}
                <div>
                    <input class="button" style="width:100%;" type="submit" value="Claim Gift"></input>
                </div> 
            </form>
            <div>
                <a href="{% url 'main:list_gifts' gift.owner.id %}" class="button" style="width:100%;">Return to Wishlist</a>
            </div>
        </div>
        {% endif %}
    </section>
</article>

{% endblock %}